_base_: '../_base_/coco_stuff.yml'


model:
  type: PointRend
  backbone:
    type: ResNet50_vd
    output_stride: 8
    pretrained: 'scnet50.pth'
  backbone_indices: [0, 1, 2, 3]


loss:
  types:
    - type: CrossEntropyLoss
    - type: PointCrossEntropyLoss
  coef: [1, 1]


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005
